name: Setup Python Environment
description: Setup Python 3.13 with pip caching and install dependencies

inputs:
  install-deps:
    description: 'Whether to install requirements.txt dependencies'
    required: false
    default: 'true'
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: pip install -r requirements.txt

