name: Build Base Image

on:
  push:
    branches:
      - master
    paths:
      - 'requirements.txt'
      - 'docker/Dockerfile.base'
      - '.github/workflows/base-image.yml'
  pull_request:
    branches:
      - master
  workflow_dispatch:

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BASE_IMAGE: sanjibdevnath/ragtrial-base

jobs:
  build-base-image:
    name: Build and Push Base Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get commit SHA
        id: sha
        run: echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
      
      - name: Check if base image exists
        id: check
        run: |
          if docker manifest inspect ${{ env.BASE_IMAGE }}:${{ github.sha }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ Base image already exists for commit ${{ github.sha }}"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "🔨 Need to build base image for commit ${{ github.sha }}"
          fi
      
      - name: Extract metadata
        if: steps.check.outputs.exists == 'false'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BASE_IMAGE }}
          tags: |
            type=sha,format=long
      
      - name: Build and push base image
        if: steps.check.outputs.exists == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Image details
        run: |
          if [ "${{ steps.check.outputs.exists }}" = "true" ]; then
            echo "✅ Base image already exists (skipped build)"
          else
            echo "✅ Base image built and pushed successfully!"
          fi
          echo ""
          echo "📦 Image: ${{ env.BASE_IMAGE }}:${{ github.sha }}"
          echo "🔒 Commit-specific tag ensures isolation between branches/PRs"
          echo ""
          echo "💡 Use in workflows:"
          echo "    container: ${{ env.BASE_IMAGE }}:${{ github.sha }}"

