name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Cache linting tools
        uses: actions/cache@v4
        id: cache-lint
        with:
          path: ~/.cache/pip
          key: lint-tools-${{ runner.os }}-black-flake8-isort-mypy-v1
          restore-keys: |
            lint-tools-${{ runner.os }}-
      
      - name: Install dependencies
        if: steps.cache-lint.outputs.cache-hit != 'true'
        run: pip install black flake8 isort mypy
      
      - name: Check code formatting with Black
        run: make black-check
      
      - name: Check import sorting with isort
        run: make isort-check
      
      - name: Lint with Flake8
        run: make flake8-check

