name: Tests & Coverage

on:
  workflow_run:
    workflows: ["Build Base Image"]
    types:
      - completed
    branches: [ master, develop ]

env:
  BASE_IMAGE: sanjibdevnath/ragtrial-base

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: sanjibdevnath/ragtrial-base:${{ github.sha }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run unit tests with coverage
        run: make test-ci
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-ragtrial
          fail_ci_if_error: true
      
      - name: Coverage comment on PR
        if: github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 80
      
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
  
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: sanjibdevnath/ragtrial-base:${{ github.sha }}
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_ragtrial
          MYSQL_USER: test_ragtrial
          MYSQL_PASSWORD: test_ragtrial
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup test database
        run: |
          mysql -h mysql -u root -proot < scripts/setup_test_mysql.sql
          APP_ENV=test make migrate-up
      
      - name: Run integration tests
        run: make test-integration

